// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsyk7YqNwadpT1H_xN-QgNvAopQ3F9jEo',
    appId: '1:735835056134:web:6cbe48467d6fffa534bb87',
    messagingSenderId: '735835056134',
    projectId: 'cheatapplication-fdb8e',
    authDomain: 'cheatapplication-fdb8e.firebaseapp.com',
    storageBucket: 'cheatapplication-fdb8e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrinQTpQ4XAiZRFaB6hdiyDiLQEfIbVNE',
    appId: '1:735835056134:android:b0dea41b15c025d834bb87',
    messagingSenderId: '735835056134',
    projectId: 'cheatapplication-fdb8e',
    storageBucket: 'cheatapplication-fdb8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNddQuELc3zgJwR0FQwSsCLWFBeiYcYqA',
    appId: '1:735835056134:ios:25db28c5a4488fec34bb87',
    messagingSenderId: '735835056134',
    projectId: 'cheatapplication-fdb8e',
    storageBucket: 'cheatapplication-fdb8e.firebasestorage.app',
    iosBundleId: 'com.example.cheatapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNddQuELc3zgJwR0FQwSsCLWFBeiYcYqA',
    appId: '1:735835056134:ios:25db28c5a4488fec34bb87',
    messagingSenderId: '735835056134',
    projectId: 'cheatapplication-fdb8e',
    storageBucket: 'cheatapplication-fdb8e.firebasestorage.app',
    iosBundleId: 'com.example.cheatapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsyk7YqNwadpT1H_xN-QgNvAopQ3F9jEo',
    appId: '1:735835056134:web:f5bca8736a77260b34bb87',
    messagingSenderId: '735835056134',
    projectId: 'cheatapplication-fdb8e',
    authDomain: 'cheatapplication-fdb8e.firebaseapp.com',
    storageBucket: 'cheatapplication-fdb8e.firebasestorage.app',
  );
}
